name: Build

on:
  workflow_dispatch:
  push:
    tags:
      - v*.*.*

env:
  CMAKE_VERSION: 3.24
  PYTHON_VERSION: 3.9
  NODE_VERSION: 16

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Build

    strategy:
      fail-fast: false
      matrix:
        include:
          - target: linux-aarch64-static-lib
            build-type: static-lib
            runs-on: buildjet-4vcpu-ubuntu-2204-arm

          - target: linux-x64-static-lib
            build-type: static-lib
            runs-on: ubuntu-latest

          - target: osx-arm64-static-lib
            build-type: static-lib
            runs-on: ghcr.io/cirruslabs/macos-monterey-xcode:latest

          - target: osx-x86_64-static-lib
            build-type: static-lib
            runs-on: macos-latest

          - target: win-x64-static-lib
            build-type: static-lib
            runs-on: windows-2019

          - target: wasm-static-lib
            build-type: wasm-static-lib
            runs-on: ubuntu-latest

          - target: wasm-static-lib-simd
            build-type: wasm-static-lib-simd
            runs-on: ubuntu-latest

          - target: wasm-static-lib-threaded
            build-type: wasm-static-lib-threaded
            runs-on: ubuntu-latest

          - target: wasm-static-lib-simd-threaded
            build-type: wasm-static-lib-simd-threaded
            runs-on: ubuntu-latest

    runs-on: ${{ matrix.runs-on }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup CMake
        uses: lukka/get-cmake@v3.26.0
        with:
          cmakeVersion: ${{ env.CMAKE_VERSION }}

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Setup Node
        if: startsWith(matrix.build-type, 'wasm')
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install Coreutils
        if: runner.os == 'macOS'
        run: brew install coreutils

      - name: Set ONNX Runtime version
        run: |
          if ${{ startsWith(github.ref, 'refs/tags/v') }}; then
            echo ONNXRUNTIME_VERSION=${GITHUB_REF_NAME#v} >> $GITHUB_ENV
          else
            echo ONNXRUNTIME_VERSION=$(cat onnxruntime/VERSION_NUMBER) >> $GITHUB_ENV
          fi

      - name: Build
        run: ./build-${{ matrix.build-type }}.sh

      - name: Set archive name
        run: echo ARCHIVE_NAME=onnxruntime-${{ matrix.target }}-${{ env.ONNXRUNTIME_VERSION }} >> $GITHUB_ENV

      - name: Archive (UNIX)
        if: runner.os != 'Windows'
        working-directory: outputs/${{ matrix.build-type }}
        run: tar cvfz ${{ runner.temp }}/${{ env.ARCHIVE_NAME }}.tgz .

      - name: Archive (Windows)
        if: runner.os == 'Windows'
        working-directory: outputs/${{ matrix.build-type }}
        run: 7z a "${{ runner.temp }}\${{ env.ARCHIVE_NAME }}.zip" .

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.ARCHIVE_NAME }}
          path: ${{ runner.temp }}/${{ env.ARCHIVE_NAME }}.*

  release:
    name: Release
    if: startsWith(github.ref, 'refs/tags/v')
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3

      - name: Release
        uses: ncipollo/release-action@v1
        with:
          body: "Official Release: [ONNX Runtime ${{ github.ref_name }}](https://github.com/microsoft/onnxruntime/releases/tag/${{ github.ref_name }})"
          artifacts: "**/*.*"
          allowUpdates: true
